export const metadata = {
    title: "Entertainment web app",
    description: "Generated by Next.js",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>               
                {children}
            </body>
        </html>
    );
}
